### ISSUE TITLE
Coway changed auth backends (I think)

### ISSUE THREAD

**Issue by mckern** [RobertD502/home-assistant-iocare#12]
Looks like the official iOS app made everyone migrate to a Coway account this week. The error I get from the integration when asked to reauthorize is "Coway API authentication error: unable to retrieve auth 'code'. Likely due to invalid username/password."
Please me know if there's anything I can do to help debug -- HA runs on HAOS and I can SSH to the underlying OS freely so I can get whatever logs you might need/want from my setup.

**Comment by RobertD502** [comment]
Yup, looks like they did and in turn probably changed the authorization. I'll have to sniff out the new endpoints/auth method and make those changes to the backend.

**Comment by jerrice** [comment]
Thanks @RobertD502, I'm seeing the same issue as well...

**Comment by RobertD502** [comment]
@mckern @jerrice 

After migrating your account using the Coway IoCare mobile app (note: use the same email and password for your new "coway account"), update the integration to `0.1.4`, which I just released. That should take care of things.

**Comment by tmclean** [comment]
Confirmed @RobertD502 , 0.1.4 works.

I was just troubleshooting this and saw a release from minutes ago. Perfect timing.

**Comment by sjafferali** [comment]
+1, 0.1.4 is also working for me.

**Comment by jerrice** [comment]
> Reference

Yup, works perfectly, thank you!!

**Comment by mckern** [comment]
Works perfectly for me; great turnaround time. Thank you so much!

**Comment by RobertD502** [comment]
> Works perfectly for me; great turnaround time. Thank you so much!

No problem! I realize a lot of people rely on this integration so I had to work fast. Not sure why they decided to add an openid layer, but hopefully that's the last of any major changes they make.
