### ISSUE TITLE
Retrying setup: list index out of range error.

### ISSUE THREAD

**Issue by Elderwolf1700** [RobertD502/home-assistant-iocare#13]
I am getting "Retrying setup: list index out of range" error after logging in. 
![error](https://user-images.githubusercontent.com/78251505/198815726-aeefb5b1-e350-4e30-960a-661923fcc32b.PNG)
In the logs, it shows: 

`Unexpected error fetching coway data: list index out of range
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 205, in _async_refresh
    self.data = await self._async_update_data()
  File "/config/custom_components/coway/coordinator.py", line 41, in _async_update_data
    data = await self.client.async_get_purifiers_data()
  File "/usr/local/lib/python3.10/site-packages/cowayaio/coway_client.py", line 152, in async_get_purifiers_data
    dust_pollution = state[2][1][0].get('dustPollution')
IndexError: list index out of range`

It was working before all this login stuff changed.

**Comment by RobertD502** [comment]
What Airmega model do you have?

**Comment by Elderwolf1700** [comment]
I have two AP-1512HHS's.

**Comment by RobertD502** [comment]
It is possible that Coway removed some fields for that purifier model during their last update. However, I don't own that model so I can't say for sure what was removed. If you could possibly temporarily share your account with me (not through here), I'd be able to see what is available for your models.

**Comment by Elderwolf1700** [comment]
Sure, do you have discord? I could send it to you there. Or would email be better?

**Comment by RobertD502** [comment]
Discord: RobertD502

**Comment by Elderwolf1700** [comment]
Tag number?

**Comment by RobertD502** [comment]
Apologies! RobertD502#4048

**Comment by RobertD502** [comment]
Solved: Temporary Coway server-side bug.
