### ISSUE TITLE
"Unknown error occurred" when attempting login via initial setup

### ISSUE THREAD

**Issue by chrisvanhorn** [RobertD502/home-assistant-iocare#14]
I am receiving an error during initial setup at the initial "Fill in your Coway IoCare account credentials" step.

I have the correct credentials entered for username/password, and have tried both my email and phone number. They both produce "Unknown error occurred"

**Comment by chrisvanhorn** [comment]
After trying a few more times, it seems I am also sometimes receiving a "Failed to connect to Coway servers" error instead of the "Unknown error occured" message.

**Comment by RobertD502** [comment]
1. What version of the integration are you running?
2. Have you transferred your account over to a coway account? Coway started a new login method last week that requires all previous accounts to be transferred over to a new coway account.

**Comment by chrisvanhorn** [comment]
Sorry Robert, I already restarted my HomeAssistant instance once and was still getting this error, but it seems a full reboot of my raspberry pi resolved this. Easy fix! Apologies for not trying this first before posting here.
