### ISSUE TITLE
HA integration

### ISSUE THREAD

**Issue by flochtililoch** [RobertD502/home-assistant-iocare#15]
Pardon my ignorance, but is there anything preventing from submitting this as a Home Assistant integration? (i.e. that does not need HACS). I'm not clear on what value HACS brings over regular integrations, so I might be missing something...

**Comment by RobertD502** [comment]
I'll be upfront and say that I have no plans of attempting to get this into Home Assistant. One downside to it being an official HA integration are updates - If a bug were to be found, users would have to wait for the fixe to be pushed out to them with Home Assistant updates. So, for example, if a big change were to happen today (like the recent login change) and I pushed out a fix today, users wouldn't get that fix until HA decided to release a new update to Home Assistant as a whole.

HACS gives developers more control.
