### ISSUE TITLE
Setup??

### ISSUE THREAD

**Issue by RagnarSTS** [RobertD502/home-assistant-iocare#18]
Ok I've tried it at least 6 times now.  

Install through HACS seemed fine, but won't allow setup.
Manually copied files from repo to custom_components directory.  Reboots completed after each attempt.

searching for the integration doesn't show anything whether fresh browser or not.  
Hitting the button right on the readme page.  I get this error page:  "This integration does not support configuration via the UI. If you followed this link from the Home Assistant website, make sure you run the latest version of Home Assistant."

Any assistance or hints would be appreciated.

**Comment by RobertD502** [comment]
Did you have another iocare integration set up at some point in time?

**Comment by RagnarSTS** [comment]
Definitely had the old one pre-changes.  It has been removed; or at least I thought it was.

**Comment by RobertD502** [comment]
I would go ahead and delete the old integration (both from the integrations screen if it is set up there and any traces in the custom_components folder). Once you don't have the coway integration on the integrations page or the coway folder in the custom_components folder, restart Home Assistant. Then go into HACS and redownload the integration from this repo. Once you have done so, be sure to clear the cache/reload your browser window followed by another Home Assistant restart. 

The only time I have seen such an error is when a user has another integration installed under the same domain name (coway in this case), which is interfering with the new integration.

**Comment by RagnarSTS** [comment]
Completed again.  This time it gives me the error about "Coway API authentication error: unable to retrieve auth 'code'. Likely due to invalid username/password."  ... which sounds more like the old integration, but definitely this one.

**Comment by RagnarSTS** [comment]
I assure you the email and pass were correct.

**Comment by RagnarSTS** [comment]
So Coway's internet presence is a mess...crapass cowaymega.com seems the most logical login place - is this incorrect?  The website looks so rough it seems like a hoax site with mousing over the little round person icon that brings you to account having a popup tooltip that says 'User icon' and little handbag icon showing tooltip 'Cart icon'.  
I tried to login to the old system and 'migrate' but that thing completely ate crap and didn't work....so maybe I'm just in the wrong place?

**Comment by RobertD502** [comment]
You need to use the mobile app and transfer your old account to a new Conway account prior to using this integration.

**Comment by RagnarSTS** [comment]
Well there we go then. App hasn't been able to sign in for months. Might as well close as coway has screwed up authentication too hard.

**Comment by RobertD502** [comment]
I guess I'm not understand the issue here. There is a button at the login screen (on the iocare app) to transfer your account.

**Comment by RagnarSTS** [comment]
No worries.  Not your issue.  
Not sure how much more clear I can be...the app hasn't been able to sign in.  So if it doesn't function...can't transfer...might as well replace this stupid piece of junk with a $100 purifier.

**Comment by RobertD502** [comment]
I'd suggest getting in contact with their support team. Best of luck!
