### ISSUE TITLE
entities unavailable after installing

### ISSUE THREAD

**Issue by StarFox2873** [RobertD502/home-assistant-iocare#2]
This integration looks great, upgrading from the Sarahhenkens version and i am having some trouble.
I uninstalled the old version
deleted the integration 
rebooted (after installing in hacs)
added integration, entered my password etc..
It found my two Coway 400's and added them and all of the entities are unavail.
Tried rebooting
Tried removing and re-adding integration.
Appreciate any help you can provider

Logs:
Logger: homeassistant.components.select
Source: custom_components/coway/select.py:83
Integration: Select (documentation, issues)
First occurred: 8:41:34 AM (4 occurrences)
Last logged: 8:42:47 AM

Error adding entities for domain select with platform coway
Error while setting up coway platform for select
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 521, in _async_add_entity
    original_icon=entity.icon,
  File "/config/custom_components/coway/select.py", line 75, in icon
    if self.current_option is "OFF":
  File "/config/custom_components/coway/select.py", line 83, in current_option
    return IOCARE_TIMERS_TO_HASS.get(self.coordinator.data[self._device].timer)
AttributeError: 'Purifier' object has no attribute 'timer'

**Comment by smmalis37** [comment]
What version of HomeAsssistant are you on?

**Comment by StarFox2873** [comment]
Home Assistant 2022.2.9

**Comment by StarFox2873** [comment]
I just went back into hacs and see that i somehow did not delete the old version so i must have had both installed at once.  I have tried to remove it now, remove both and restarted.  Still getting the same result.

**Comment by StarFox2873** [comment]
I was able to get it working, reset the wifi connection on both devices.  It was working previously so that was odd.  Thanks for all of the effort that went into this integration.

**Comment by RobertD502** [comment]
@StarFox2873 My apologies. I forgot to set up notifications for this repo, so, I didn't see you opened up an issue. Purifiers show as unavailable whenever Coway's servers show that they don't have an active connection to the Purifiers.

I'll need to modify the backend to handle the attribute exception better and log the possibility of a purifier being offline.

**Comment by RobertD502** [comment]
Pushing a release shortly to properly log if a purifier is offline. Thanks for bringing this to my attention.

**Comment by StarFox2873** [comment]
Thank you!
