### ISSUE TITLE
RFE: add support for disabling the "offline" error reporting in v0.1.9

### ISSUE THREAD

**Issue by pcmoore** [RobertD502/home-assistant-iocare#21]
First off, I want to thank you for creating this component and maintaining it; it's been a great help for us.

In the latest release, v0.1.9, I see commit 4f01da87c556c3c9d5a403ee5476aeabd8454569 which generates an error log whenever a device is marked as being 'offline'.  Unfortunately in our home some of our purifiers sporadically drop their connection for a few minutes once or twice a day.  While annoying, in practice it has been easy enough to work around this in automatons, monitoring scripts, etc., but I worry that logging an error message will generate an excessive amount of error/notification noise in HA.  Would it be possible to add a configuration toggle to disable this logging?

Regardless, thanks again for all the time and effort you've put into this!

**Comment by RobertD502** [comment]
Thanks for using this integration!

I wouldn't worry about it generating a lot of noise in Home Assistant.  Within the Home Assistant log UI, if an error is logged multiple times, it is presented visually only once. So, you won't have to worry about it cluttering the Home Assistant Logs UI.

For example:
![image](https://user-images.githubusercontent.com/52541649/231281267-0210c20c-f9b9-409b-8260-68af172b2bc9.png)
As you can see, although the error was logged 3 times, only a single UI element is created.

If you still want to completely ignore logging this error, comment out `line 151` in `fan.py`

**Comment by pcmoore** [comment]
It will still raise a notification in the web UI about the new error, right?  If not, nevermind :)

**Comment by RobertD502** [comment]
Nope! 

It will only be logged to the HA logs / visible in the logs section of the HA UI. Only very important scenarios like an Authorization error prompting the reauth flow will raise a notification in the web UI for this integration.

**Comment by pcmoore** [comment]
Perfect, thanks for the clarification and sorry about the noise!

**Comment by RobertD502** [comment]
Not a problem at all!
