### ISSUE TITLE
Can't login: coway servers did not return a valid login URL

### ISSUE THREAD

**Issue by gdudek** [RobertD502/home-assistant-iocare#22]
This was working great when I configured it 2 days ago (and continued to work). 
Then I power cycled everything today and now I cannot connect, but I can still connect via the phone-based app.

I see:
   Failed setup: will retry.
  On hovering over the error I see: Can't login: coway servers did not return a valid login URL

**Comment by RobertD502** [comment]
Power cycled your purifier(s) or Home Assistant?

That error just means that the Coway servers aren't returning a login URL which is needed to proceed with logging in. I'd reload the integration and see if you can get it go. Aside from that, we don't have any control over what the coway servers return.

**Comment by RobertD502** [comment]
Let me know if it starts behaving again.

**Comment by gdudek** [comment]
Thanks.  Power cycled the purifier (which seemed unlikely to help), removed the integration and re-added it (without success since I cant login and now it's not loaded at all), power cycled HA.   I am out of debugging actions.  I'd try the URL manually, but didn't find it in the code -- my bad, as it's obviously in there somewhere!

I even try the  pypi iocareapi.py package as a debugging step, but it's old and doesn't seem to the use the same API.

Around the time this all fell apart, I did register the purifier at coway.com via my browser as well.  Is there any way that might have interfered?

**Comment by RobertD502** [comment]
@gdudek Send me a message on Discord @RobertD502 since this may take a bit of troubleshooting.

Side note: The integration uses the `cowayaio` library.

**Comment by RobertD502** [comment]
> Well, it started to work again.  I presume there was a glitch on the Coway end of pipeline.  Thanks for your help.  I will think about some method to intercept via the router and do fully local control, but thats a big undertaking.  Thanks!

Some work has already been done [here](https://joshspicer.com/hack-air-purifier), but it stops short of actually controlling it.
