### ISSUE TITLE
Unable to change speed settings

### ISSUE THREAD

**Issue by LightningXCE** [RobertD502/home-assistant-iocare#23]
Device: AIRMEGA 400S Graphite
Home Assistant 2023.8.0
Supervisor 2023.07.1
Operating System 10.4

Recently, it seems like control over the purifier in HA is not working as intended - I am getting data _from_ the purifier, but I am unable to control it from any part of the UI.

https://github.com/RobertD502/home-assistant-iocare/assets/720172/cc2a5e78-3bbd-4337-a19c-e4d7d2e52a8f

I have power cycled both HA and the purifier itself, re-authenticated, etc, and it seems to just... stick on whatever I set it to physically. 

I am unsure where to look for logs to help try to diagnose this. Seems like within the last few days this just tripped up and I am just noticing now.

**Comment by RobertD502** [comment]
The only time I've ever seen this is when the purifier and server have gone out of sync, but a quick cycle of the purifier fixes that issue, which you have already done.

Out of curiosity, when you change the speed via HA, does the purifier change to that speed physically?

**Comment by LightningXCE** [comment]
It does not, no. It's almost like it never "gets" the command.

I ended up power cycling my entire system again, as well as an unwilling cycle due to losing power from a storm that just blew through, and it... is working again? I guess it just remained out of sync somehow through my other restarts.

So yeah, potential false alarm. Thanks again for maintaining this integration, it's awesome to see!

**Comment by RobertD502** [comment]
No problem! Although out of sync issues aren't great, they aren't too common.
