### ISSUE TITLE
Login with Google SSO

### ISSUE THREAD

**Issue by Natclanwy** [RobertD502/home-assistant-iocare#3]
My IOcare account is setup with a google sign in, is there a way to login using this method? There doesn't appear to be a way to setup a normal user name and password on IO Care without deleting my account and starting a new one.

**Comment by RobertD502** [comment]
Unfortunately, this doesn't work with any accounts created through any of the third party options. An account that is directly created through coway is required.

**Comment by Natclanwy** [comment]
Thank You for the reply, I figured out how to add another account using my phone number instead of my email and was able to get it setup.
