### ISSUE TITLE
No fan speed / smart controls for 400S? 

### ISSUE THREAD

**Issue by edude03** [RobertD502/home-assistant-iocare#33]
Hey, thanks for your great work on this integration. 

Not sure if I'm being an idiot, but after setting up the integration seems like I don't have the "Smart/Sleep" and "Fan Speed" controls the app does, is this expected? My goal is to automatically switch to sleep mode at night like the app can for reference. 
![IMG_3641](https://github.com/RobertD502/home-assistant-iocare/assets/494483/35c0861f-bbc7-4ce8-8e36-243a9d3bae2e)
![IMG_3642](https://github.com/RobertD502/home-assistant-iocare/assets/494483/1c0cd00e-3c2e-4298-b6cd-aa6601707c3c)

**Comment by RobertD502** [comment]
Click on the fan entity "Purifier". There you will see a preset for "Auto" mode to go into auto mode as well as fan speed. You will need to make service calls on this entity if doing it by automation.

**Comment by edude03** [comment]
Thanks, happy I was just being an idiot!
