### ISSUE TITLE
Failed setup, will retry - Coway API error

### ISSUE THREAD

**Issue by rd778** [RobertD502/home-assistant-iocare#37]
Hello,

I've just added two devices to the integration. The first one added fine with no trouble. However, the second one fails to connect to Home Assistant "failed setup, will retry". 

Looking at the logs, I'm getting this message: "Error fetching coway data: Coway API error: Coway server failed to return purifier quality status."

Any suggestions to get this working? I wondered if the issue was because I had two devices on one account, so I added the second device to a new IOCare account and added it to HA as a new "hub". The issue still happens. 

Thanks!

**Comment by RobertD502** [comment]
There will be a release here shortly. The issue stems from some purifiers that were recently purchased not working with the old API (at least only for the quality endpoint).

If you have a purifier on your account that does work with the older API and then add a purifier that doesn't, the integration fails. So, the issue isn't with having multiple purifiers on a single account as this is completely fine. Feel free to add all of your purifiers to a single account. Once I release version `0.4.0` (it'll be within the next ~30min - 1 hour), install it and then try again.

**Comment by RobertD502** [comment]
Please download & install `0.4.0`. This should solve your issue.

**Comment by rd778** [comment]
Thank you. Yes, I'm no longer getting that error message (instead I'm now getting issue #39 ), so looks like this particular issue resolved. Thanks!

**Comment by RobertD502** [comment]
> Thank you. Yes, I'm no longer getting that error message (instead I'm now getting issue #39 ), so looks like this particular issue resolved. Thanks!

`0.4.1` resolves the new issue.
