### ISSUE TITLE
Convert empty string to float error

### ISSUE THREAD

**Issue by romedtino** [RobertD502/home-assistant-iocare#5]
Hi Robert,

First thanks for maintaining this integration! I just installed it and I seem to be running into an issue where it is trying to convert an empty string to a float specifically in this line: https://github.com/RobertD502/home-assistant-iocare/blob/f90d1037e4a79ea6471fd6295cedf8c98bd09cbf/custom_components/coway/sensor.py#L241

I can reproduce the error seen in the log if I just switch the `Preset Mode` to `auto`  or even toggle the light on/off which the commands end up not executing because of the error.  Seems to be related to AQI and I do notice for some reason my `sensor.airmega_aqi` is showing unavailable.  

Is this a bug or is there something perhaps I'm missing regarding the setup? Thanks!

**Comment by RobertD502** [comment]
Please post any related logs here. The preset mode and light switch are separate from the AQI sensor, so this line shouldn't be having any impact on those function. Regarding the sensor being unavailable - this isn't a bug. If the coway servers are reporting your purifier as not connected to their servers then the entities related to the purifier become unavailable. They become available again once Coway's servers report the purifier as being connected to their servers again.


To further narrow down your issue, as said before, please post any related logs (including anything regarding changing the preset mode, turning light on/off).

Also, just to make sure - are you using either a 300S or 400s purifier? If you are using their new purifier (I believe it is the 250S?), I can't confirm that this integration will work as I don't have access to one/wrote the code for the 300S and 400s.

**Comment by romedtino** [comment]
I have the AirMega 400S White. Software Version : `MCU: V1.0.0.2( 2022.03.23 16:31)`

I don't believe I saw anything in the logs regarding being disconnected but I can't rule it out.

Here' a complete log after startup and trying to toggle the light entity

<details>

```
2022-03-24 00:13:04 ERROR (MainThread) [homeassistant.components.sensor] Error adding entities for domain sensor with platform coway
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 372, in state
value = self.native_value
File "/config/custom_components/coway/sensor.py", line 241, in native_value
return round(float(self.coordinator.data[self._device].quality["air_quality_index"]), 1)
ValueError: could not convert string to float: ''
2022-03-24 00:13:04 ERROR (MainThread) [homeassistant.components.sensor] Error while setting up coway platform for sensor
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 372, in state
value = self.native_value
File "/config/custom_components/coway/sensor.py", line 241, in native_value
return round(float(self.coordinator.data[self._device].quality["air_quality_index"]), 1)
ValueError: could not convert string to float: ''
2022-03-24 00:13:36 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 372, in state
value = self.native_value
File "/config/custom_components/coway/sensor.py", line 241, in native_value
return round(float(self.coordinator.data[self._device].quality["air_quality_index"]), 1)
ValueError: could not convert string to float: ''
2022-03-24 00:13:40 ERROR (MainThread) [homeassistant.components.websocket_api.http.connection] [139928036300496] could not convert string to float: ''
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
await hass.services.async_call(
File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
task.result()
File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
await self.hass.helpers.service.entity_service_call(
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 671, in entity_service_call
future.result() # pop exception if have
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
await coro
File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 708, in _handle_entity_call
await result
File "/config/custom_components/coway/switch.py", line 76, in async_turn_off
await self.coordinator.async_request_refresh()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 141, in async_request_refresh
await self._debounced_refresh.async_call()
File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 78, in async_call
await task
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
await self._async_refresh(log_failures=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 372, in state
value = self.native_value
File "/config/custom_components/coway/sensor.py", line 241, in native_value
return round(float(self.coordinator.data[self._device].quality["air_quality_index"]), 1)
ValueError: could not convert string to float: ''
```

</details>

**Comment by RobertD502** [comment]
Ok, so based on the logs it is unavailable because the coway server is returning an empty AQI - this is odd behavior as it should never be empty. 

Can you press and hold the WiFi button on your Airmega 400S to turn off WiFi, press the button again to turn WiFi on and wait for it to reconnect to your network. After it reconnects, restart Home Assistant and let me know if the problem persists. Forcing the purifier to reconnect to Coway's servers may help getting the AQI to update properly.

**Comment by romedtino** [comment]
Still no luck :( It's getting late here but let me keep playing with it. I even tried commenting out adding the AQI entity in sensor.py which prevents the error but toggling fan/light don't seem to work. I'll keep poking at it and I'll let you know what I find. Thanks!

**Comment by RobertD502** [comment]
It was around 3 AM when I saw your initial post and I misread thinking all of the entities related to a purifier appeared as unavailable. Just to clarify, if the coway servers are reporting your purifier(s) as not connected then all entities related to the purifier(s) will be unavailable - this isn't a bug. However, in your case, just the AQI sensor entity is appearing as unavailable, which isn't normal behavior.

Where did you obtain your Software Version from? I checked all the server endpoints but wasn't able to find a key related to software version for either of my two purifiers. I think for starters we need to determine if your purifier is using a more recent version and, if so, if it uses different endpoints.

**Comment by romedtino** [comment]
I just grabbed the version info from the ioCare app (using Android app) there was a tab called Device Management and under Product Software Version it listed that MCU information. On the back of the device it reads `400S (AP-2015E)`

I was hoping it was some connection problem or it just needed more data before it started displaying the AQI information. I hoped I would wake up today seeing it magically work after a restart of HA but no dice :(.

I tried toggling WiFi, rejoining my WiFi to see if it would change behavior but it didn't seem to do much. The controls seem to work alright through the app so it could perhaps be a version change as you suspect?

**Comment by RobertD502** [comment]
Ahhhhh this info isn't listed in the iOS app. I'll have to dig out an android tablet I have laying around and check the version there. In the meantime, would you feel comfortable sharing your account with me via email (changing the password before I use it and then changing it back to your original password when I am done)? I'll need it to sniff out what endpoints the app is using for your purifier to determine if there is a difference.

**Comment by RobertD502** [comment]
Went to the Device Management tab (on the Android app) which shows the Max2 and Prefilter life. On that page I clicked on product settings. No Product Software Version listed on either the main Device Management tab or the product settings page.

**Comment by theglus** [comment]
My Airmega 400S is generating a similar error:

```
Logger: homeassistant.components.websocket_api.http.connection
Source: custom_components/coway/sensor.py:241
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 3:45:20 PM (1 occurrences)
Last logged: 3:45:20 PM

[547932243472] could not convert string to float: ''
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 192, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1636, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1673, in _execute_service
    await cast(Callable[[ServiceCall], Awaitable[None]], handler.job.target)(
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 204, in handle_service
    await self.hass.helpers.service.entity_service_call(
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 668, in entity_service_call
    future.result()  # pop exception if have
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 949, in async_request_call
    await coro
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 705, in _handle_entity_call
    await result
  File "/config/custom_components/coway/fan.py", line 151, in async_turn_off
    await self.coordinator.async_request_refresh()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 141, in async_request_refresh
    await self._debounced_refresh.async_call()
  File "/usr/src/homeassistant/homeassistant/helpers/debounce.py", line 78, in async_call
    await task
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 165, in async_refresh
    await self._async_refresh(log_failures=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 372, in state
    value = self.native_value
  File "/config/custom_components/coway/sensor.py", line 241, in native_value
    return round(float(self.coordinator.data[self._device].quality["air_quality_index"]), 1)
ValueError: could not convert string to float: ''
```

**Comment by RobertD502** [comment]
Unfortunately, I won't be able to track down what is causing the issue without access to an affected account. I have tested it with a 400S that I have access to, but it isn't experiencing the reported issue. This leads me to believe that some 400s purifiers may be running a different software version and I will need to investigate the communication between purifier and coway servers in order resolve the problem.

**Comment by romedtino** [comment]
Hi @RobertD502,

Sorry for the late reply. I am unsure if I am able to share my account but I was able to sniff some of the information which I think could prove useful.

I think there's a new endpoint `CWIG0009`. Here's the JSON dump with some PI removed

<details>

```json
{
  "body": {
    "supportAreaFlag": true,
    "weatherKR": [],
    "airnowUS": [
      {
        "list": [
          {
            "ParameterName": "CO",
            "Latitude": "34",
            "Longitude": "-118",
            "AQI": "99",
            "CategoryNumber": "1",
            "CategoryName": "Excellent",
            "CategoryTotCnt": "5",
            "NationCd": "US",
            "ReportingArea": "",
            "StateCode": "",
            "LocalTimeZone": "",
            "HourObserved": "03",
            "DateObserved": "2022-03-29"
          },
          {
            "ParameterName": "NO2",
            "Latitude": "34",
            "Longitude": "-118",
            "AQI": "86",
            "CategoryNumber": "1",
            "CategoryName": "Excellent",
            "CategoryTotCnt": "5",
            "NationCd": "US",
            "ReportingArea": "",
            "StateCode": "",
            "LocalTimeZone": "",
            "HourObserved": "03",
            "DateObserved": "2022-03-29"
          },
          {
            "ParameterName": "O3",
            "Latitude": "34",
            "Longitude": "-118",
            "AQI": "68",
            "CategoryNumber": "2",
            "CategoryName": "Good",
            "CategoryTotCnt": "5",
            "NationCd": "US",
            "ReportingArea": "",
            "StateCode": "",
            "LocalTimeZone": "",
            "HourObserved": "03",
            "DateObserved": "2022-03-29"
          },
          {
            "ParameterName": "PM10",
            "Latitude": "34",
            "Longitude": "-118",
            "AQI": "65",
            "CategoryNumber": "2",
            "CategoryName": "Good",
            "CategoryTotCnt": "5",
            "NationCd": "US",
            "ReportingArea": "",
            "StateCode": "",
            "LocalTimeZone": "",
            "HourObserved": "03",
            "DateObserved": "2022-03-29"
          },
          {
            "ParameterName": "PM2.5",
            "Latitude": "34",
            "Longitude": "-118",
            "AQI": "86",
            "CategoryNumber": "1",
            "CategoryName": "Excellent",
            "CategoryTotCnt": "5",
            "NationCd": "US",
            "ReportingArea": "",
            "StateCode": "",
            "LocalTimeZone": "",
            "HourObserved": "03",
            "DateObserved": "2022-03-29"
          },
          {
            "ParameterName": "SO2",
            "Latitude": "34",
            "Longitude": "-118",
            "AQI": "100",
            "CategoryNumber": "1",
            "CategoryName": "Excellent",
            "CategoryTotCnt": "5",
            "NationCd": "US",
            "ReportingArea": "",
            "StateCode": "",
            "LocalTimeZone": "",
            "HourObserved": "03",
            "DateObserved": "2022-03-29"
          }
        ],
        "laqiList": [
          {
            "ParameterName": "o3",
            "Latitude": "34",
            "Longitude": "-118",
            "AQI": "38",
            "CategoryNumber": "1",
            "CategoryName": "Good",
            "CategoryTotCnt": "6",
            "NationCd": "US",
            "ReportingArea": "",
            "StateCode": "",
            "LocalTimeZone": "",
            "HourObserved": "03",
            "DateObserved": "2022-03-29"
          }
        ]
      }
    ],
    "stationCd": "",
    "admdongCd": "",
    "stationAdress": ""
  },
  "header": {
    "accessToken": "REMOVED",
    "error_code": "",
    "error_text": "",
    "info_text": "",
    "login_session_id": "",
    "message_version": "",
    "refreshToken": "REMOVED",
    "result": true,
    "trcode": "CWIG0009"
  }
}
```

</details>

I think I also see that MCU version I had mentioned in endpoint `CWIG0615`. Here's a sample JSON

<details>

```json
{
    "body": {
      "updateState": "NONE",
      "newestMcuVer": null,
      "newestWifiVer": null,
      "isShowResveUpdateMessage": false,
      "curUpdateDate": 1648078318868,
      "curMcuVer": "V1.0.0.2",
      "curWifiVer": "4889",
      "resveUpdateDate": 0
    },
    "header": {
      "accessToken": "REMOVED"
      "error_code": "",
      "error_text": "",
      "info_text": "",
      "login_session_id": "",
      "message_version": "",
      "refreshToken": "REMOVED",
      "result": true,
      "trcode": "CWIG0615"
    }
  }
```

</details>

Hope this helps! I'm guessing there will need to be a way to figure out if the 400S version is the newer ones with different endpoints? Hopefully that second JSON or there's some way to figure that out. Let me know if I can help more!

**Comment by RobertD502** [comment]
I have the `CWIG0009` endpoint, but that isn't where AQI for the unit is obtained from. That endpoint serves outdoor air quality measurements and not those obtained by the purifier itself.

I can confirm that I do not have the `CWIG0615` endpoint.

**Comment by romedtino** [comment]
Oh, I see. odd then, perhaps these new 400S units need some update because all of the IAQ section definitely just comes in blank :(

**Comment by RobertD502** [comment]
What does your `CWIA0120` endpoint json look like? In particular, the `IAQ` section:

![image](https://user-images.githubusercontent.com/52541649/160532456-01b486da-1449-476f-8fdc-eb6e0892fadd.jpeg)

**Comment by romedtino** [comment]
The keys are there but the values except for dustpm10 are blank
```json
"IAQ": [
      {
        "co2": "",
        "inairquality": "",
        "humidity": "",
        "dustpm25": "",
        "temperature": "",
        "dustpm10": "25",
        "dustpm1": "",
        "vocs": ""
      }
    ],
    "OAQ": []
```

just invoking `iocareapi.py` on its own, I also noticed the control commands don't work unless I add `mqttRequest: True`  in the request body. 

```py
def control(self, device, command, value):
        response = self._request(CONTROL, {
            'barcode': device.device_id,
            'dvcBrandCd': device.device_brand,
            'prodName': device.product_name,
            'dvcTypeCd': device.device_type,
            'funcList': [{
              'comdVal': value,
              'funcId': command
            }],
            'mqttDevice': True
        })
```

**Comment by romedtino** [comment]
So with the info above, I kind of got it partially working on Home Assistant with some kludging:

- I removed the AQI sensor (commenting out this entry https://github.com/RobertD502/home-assistant-iocare/blob/f90d1037e4a79ea6471fd6295cedf8c98bd09cbf/custom_components/coway/sensor.py#L36)  
- I added `mqttDevice: True` in `iocareapi.py` (appended to this line: https://github.com/RobertD502/pyiocare/blob/4db37d46de23aab30ebe9d408332c76585527710/iocare/iocareapi.py#L215)

The functionality seems to work sans the AQI information.

**Comment by RobertD502** [comment]
It should work without just the AQI sensor. Home Assistant tried to update info for all sensors when any control functions are called which is why yours hangs up when it fails to update the AQI in the process. 

The MQTT portion shouldn't be necessary - it is also sent for my purifiers, but still works without it (the library was created with a lower iOS version app before they started using that option).

**Comment by RobertD502** [comment]
Does your report section look like this?:

![image](https://user-images.githubusercontent.com/52541649/160652971-6dce3b23-046e-44b7-9984-6af588744b57.png)

If so, that means the purifier has to be reporting AQI to the Coway servers...the issue is where.

**Comment by romedtino** [comment]
Yea, I have those too 
<img src="https://user-images.githubusercontent.com/18567128/160662683-67a70801-4e7e-427f-b2e2-aaa6cbab320b.png" width="500">

But the only thing populated in the `CWIA0120` section which has some semblance of AQI is that pm10Graph section, here's a snippet. 

<details>

```json
"pm10Graph":[
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290320",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290330",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290340",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"None",
            "place":"in",
            "msrdt":"202203290350",
            "graphvalue":"None"
         },
         {
            "graphhighvalue":"10",
            "place":"in",
            "msrdt":"202203290400",
            "graphvalue":"1"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290410",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290420",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290430",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290440",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290450",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"10",
            "place":"in",
            "msrdt":"202203290500",
            "graphvalue":"1"
         },
         {
            "graphhighvalue":"9",
            "place":"in",
            "msrdt":"202203290510",
            "graphvalue":"1"
         },
         {
            "graphhighvalue":"17",
            "place":"in",
            "msrdt":"202203290520",
            "graphvalue":"2"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290530",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290540",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"13",
            "place":"in",
            "msrdt":"202203290550",
            "graphvalue":"1"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290600",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290610",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290620",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290630",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290640",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290650",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290700",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"7",
            "place":"in",
            "msrdt":"202203290710",
            "graphvalue":"1"
         },
         {
            "graphhighvalue":"12",
            "place":"in",
            "msrdt":"202203290720",
            "graphvalue":"2"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290730",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290740",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"None",
            "place":"in",
            "msrdt":"202203290750",
            "graphvalue":"None"
         },
         {
            "graphhighvalue":"7",
            "place":"in",
            "msrdt":"202203290800",
            "graphvalue":"1"
         },
         {
            "graphhighvalue":"4",
            "place":"in",
            "msrdt":"202203290810",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"15",
            "place":"in",
            "msrdt":"202203290820",
            "graphvalue":"2"
         },
         {
            "graphhighvalue":"6",
            "place":"in",
            "msrdt":"202203290830",
            "graphvalue":"1"
         },
         {
            "graphhighvalue":"18",
            "place":"in",
            "msrdt":"202203290840",
            "graphvalue":"3"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290850",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"46",
            "place":"in",
            "msrdt":"202203290900",
            "graphvalue":"8"
         },
         {
            "graphhighvalue":"0",
            "place":"in",
            "msrdt":"202203290910",
            "graphvalue":"0"
         },
         {
            "graphhighvalue":"25",
            "place":"in",
            "msrdt":"202203290920",
            "graphvalue":"4"
         }
      ],
```

</details>

If I'm understanding it right, is `"place":"in"` here meaning the indoor AQI value? This might be the only thing provided now for these newer models perhaps? The values I have here seem to match this graph in the Home tab. At least comparing that fairly high value between 8 and 9 which looks to have that graphhighvalue of 46?
<img src="https://user-images.githubusercontent.com/18567128/160664288-ca60120a-13f9-4bfe-9f41-c58783eec36c.png" width="500">

**Comment by RobertD502** [comment]
Maybe they'll update it down the line. For now it seems the newer models won't have AQI sensors - It is a bit puzzling why they chose to report PM10, but not anything else.

**Comment by RobertD502** [comment]
Just an update:

Even though my purifiers don't call the `CWIG0615` endpoint, I made a manual call using the backend library and it returns:

`{'updateState': '', 'newestMcuVer': None, 'newestWifiVer': None, 'isShowResveUpdateMessage': False, 'curUpdateDate': 0, 'curMcuVer': None, 'curWifiVer': None, 'resveUpdateDate': 0}`

So, I can use this endpoint to determine if a user has an older model or the updated model.

**Comment by RobertD502** [comment]
@romedtino @theglus 

I just released a `0.0.3.2 pre-release` and need to have it tested with your new units before I release it in the wild.

First of all, I need to test if everything works out from onboarding, so, I will need for you all to
please delete the integration (from the Home Assistant integration page) if you currently have it set up.

After doing so, go to HACS, select `Integrations` and find the Coway integration card. On the coway card, select the overflow menu (three vertical dots) and click on `redownload`. After doing so be sure `Show beta versions` is selected. You should then be able to select version `0.0.3.2`. Install it, restart Home Assistant, and set the integration up through the Home Assistant integrations page.

Things I need tested:

- Confirm that an AQI sensor is not created for your purifier
- Test turning purifier on and off
- Test turning purifier light on and off
- Test setting purifier preset mode to auto and to night
- Test setting purifier fan speed to each of the three levels as well as 0 (this should turn the purifier off)
- Test setting the timer to 1 hour, 2 hours, 4 hours, and 8 hours. Also setting the timer to off.

I appreciate the help!

**Comment by theglus** [comment]
@RobertD502 Awesome, thanks for the quick turn-around time. I'm out of the house now, but I'll put together a testing report with my results when I get home.

**Comment by romedtino** [comment]
I verified the list you mentioned

* [x] Confirm that an AQI sensor is not created for your purifier
* [x] Test turning purifier on and off
* [x] Test turning purifier light on and off
* [x] Test setting purifier preset mode to auto and to night
* [x] Test setting purifier fan speed to each of the three levels as well as 0 (this should turn the purifier off)
* [x] Test setting the timer to 1 hour, 2 hours, 4 hours, and 8 hours. Also setting the timer to off.

While the control of it worked, I would get this as an error in the HA logs for every command

```
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 134, in _handle_refresh_interval
await self._async_refresh(log_failures=True, scheduled=True)
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 265, in _async_refresh
update_callback()
File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 325, in _handle_coordinator_update
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
state = self._stringify_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
if (state := self.state) is None:
File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 372, in state
value = self.native_value
File "/config/custom_components/coway/sensor.py", line 225, in native_value
return round(float(self.coordinator.data[self._device].quality["air_quality_index"]), 1)
ValueError: could not convert string to float: ''
```

I had my smart mode sensitivity to `Normal`, are you thinking that affects the info we get back?

**Comment by RobertD502** [comment]
Just to confirm, you deleted the integration from the Home Assistant integrations page (not from your custom_components folder) prior to updating to 0.0.3.2 and restarting Home Assistant?

Regarding the smart mode sensitivity, can you set it to sensitive and then sniff the traffic to see if AQI is reported?

**Comment by RobertD502** [comment]
@romedtino

Make these changes to the `sensor.py` file starting at line 26, restart Home Assistant, and let me know what is logged:

```
    for idx, ent in enumerate(coordinator.data):
        _LOGGER.error(f'{coordinator.data[idx].name} is new model: {coordinator.data[idx].new_model}')
        if not coordinator.data[idx].new_model:
            _LOGGER.error(f'AQI sensor added for {coordinator.data[idx].name}')
            sensors.append(AirQualityIndex(coordinator, idx))
        sensors.append(PreFilter(coordinator, idx))
        sensors.append(MAX2Filter(coordinator, idx))
        sensors.append(TimerRemaining(coordinator, idx))
        sensors.append(ParticulateMatter25(coordinator, idx))
        sensors.append(ParticulateMatter10(coordinator, idx))
        sensors.append(CarbonDioxide(coordinator, idx))
        sensors.append(VolatileOrganicCompounds(coordinator, idx))
```

**Comment by romedtino** [comment]
Yeah, I see the new changes in my copies of custom_components/coway/* and iocareapi.py

Pulling the newer copy of iocareapi.py, trying out the new mcu_version it seems that the body key/value `'barcode': device.device_id` is now `'deviceId': device_id`. I think that might be why it's thinking the AQI sensor needs to be added because otherwise, the curMcuVer returns None

**Comment by RobertD502** [comment]
What all does the request body include for the `0615` endpoint based on your sniffing?

Are you saying that the current iocareapi backend returns None for `curMcuVer`, but a value is returned when using `'deviceId': device_id`?

**Comment by romedtino** [comment]
Sure the body for `0615`

<details>
```json
{
    "header":{
       "result":false,
       "error_code":"",
       "error_text":"",
       "info_text":"",
       "message_version":"",
       "login_session_id":"",
       "trcode":"CWIG0615",
       "accessToken": "REMOVED",
       "refreshToken": "REMOVED",
    },
    "body":{
       "deviceId":"15102DNO2191000274",
       "timezone":"America/Los_Angeles"
    }
 }
```
</details>

and yes precisely. I guess they changed it for the newer models

OLD
`'barcode': device.device_id,`

NEW
`'deviceId': device.device_id,`

otherwise, curMcuVer returns None

**Comment by theglus** [comment]
> @theglus @romedtino
> 
> Out of curiosity, what do you all have your sensitivity set to (located on the product settings page)?
> 
> I'm curious to know if perhaps settings aside from `sensitive` for newer models don't report AQI values to Coway's servers.
> 
> ![image](https://user-images.githubusercontent.com/52541649/160731067-98587418-ee0c-475d-8ef3-e04f00c4e4ef.png)

I have mine set to `sensitive`.

**Comment by RobertD502** [comment]
Alright, I can confirm that curMcuVer returns None for me when using `device_id`.  I also tested to see if the quality endpoint works when using `deviceId`, but not luck.

I'll go ahead and push the `deviceId` change to pypi and then create a new release

**Comment by RobertD502** [comment]
@theglus @romedtino 

Just released `0.0.3.3`. Let me know if that prevents the AQI sensor from being added.

**Comment by romedtino** [comment]
Can confirm no AQI sensor and no more errors for all the commands 🎉 thanks for the quick turnaround!

**Comment by theglus** [comment]
# Testing report for 0.0.33 pre-release

- [x] Deleted integration from the HA Integrations page.
- [x] Rebooted Home Assistant. 
- [x] Redownloaded Coway integration, installing beta version 0.0.3.3.
- [x] Rebooted Home Assistant. 
- [x] Confirmed that an AQI sensor is not created for your purifier
- [x] Tested turning purifier on and off
- [x] Tested turning purifier light on and off
- [x] Tested setting purifier preset mode to auto and to night
- [x] Tested setting purifier fan speed to each of the three levels as well as 0 (this should turn the purifier off)
- [x] Tested setting the timer to 1 hour, 2 hours, 4 hours, and 8 hours. Also setting the timer to off.
![Sensor List](https://user-images.githubusercontent.com/2943783/160746965-b1fc5126-5c38-47be-9389-33df87aca592.png)

**Comment by RobertD502** [comment]
Perfect! 

Thanks to both of you for helping out!

@romedtino If you don't mind, can you check the quality endpoint from time to time and report back here if an AQI ever gets populated?

**Comment by romedtino** [comment]
No problem, can do 🥳
