### ISSUE TITLE
Failed to connect to Coway servers

### ISSUE THREAD

**Issue by elstevega** [RobertD502/home-assistant-iocare#50]
On the current .4.3.2 version. Have deleted/downloaded multiple times. Every time I try to log in I get "Failed to connect to Coway servers". Can successfully login/out via the app so I know the creds are correct.

Have disabled all firewalls, adguard, suricata, etc to no avail.

This was working fine up until a week or two ago.

Any suggestions/thoughts?

thank you!

**Comment by RobertD502** [comment]
Please share any logs from the time the error occurs.

**Comment by elstevega** [comment]
Wow! That was fast! :) This is all I see in the HA logs - is there any additional info elsewhere that I am missing?

This error originated from a custom integration.

Logger: custom_components.coway
Source: custom_components/coway/util.py:36
integration: Coway IoCare (documentation, issues)
First occurred: 14:56:45 (2 occurrences)
Last logged: 15:02:24

Failed to get information from Coway servers:

**Comment by RobertD502** [comment]
There should also be a ConnectionError in your logs since it is raised after the error message above is logged.

![image](https://github.com/RobertD502/home-assistant-iocare/assets/52541649/cfe3547e-5848-4146-baa8-69fb70e92b37)

**Comment by elstevega** [comment]
No, not seeing that at all. Downloaded the entire HA core log file and nothing other than what I posted above.
[home-assistant_2024-06-01T21-15-26.305Z.log](https://github.com/user-attachments/files/15523407/home-assistant_2024-06-01T21-15-26.305Z.log)

**Comment by RobertD502** [comment]
Any chance you could share your credentials with me temporarily on discord (RobertD502)? This way we can narrow it down to if it is an integration issue or specific to your setup.

**Comment by elstevega** [comment]
yup - elsteve3007-friend request sent

**Comment by RobertD502** [comment]
Fixed by disabling IPv6 on Home Assistant machine.
