### ISSUE TITLE
TURN_OFF & TURN_ON system error log warnings requested the creation of this bug report

### ISSUE THREAD

**Issue by gh69** [RobertD502/home-assistant-iocare#52]
Warnings:
Entity None (<class 'custom_components.coway.fan.Purifier'>) does not set FanEntityFeature.TURN_OFF but implements the turn_off method. Please create a bug report at https://github.com/RobertD502/home-assistant-iocare/issues
Entity None (<class 'custom_components.coway.fan.Purifier'>) does not set FanEntityFeature.TURN_ON but implements the turn_on method. Please create a bug report at https://github.com/RobertD502/home-assistant-iocare/issues

These warnings pop up in my system error log several times after a startup and as you can see contain a request to open a bug report so here it is!  :D  I haven't noticed any actual problems using the integration though.  I'm running v0.4.3.2 of the Coway integration on HA Core 2024.8.1 with two AirMega 250S air filters and one AirMega 300S AP-1515G (US).

**Comment by RobertD502** [comment]
You'll need to update to 0.4.3.3 (released 5 days ago), which addresses the issue.

**Comment by gh69** [comment]
aha!  I didn't even notice the update in HACS!  Thanks.  I see it now and will give it a try.

**Comment by gh69** [comment]
Verified.  Installed update, restarted HA, waited for integration startup to complete, verified that integration still works as before, and checked the logs...no more errors.  Thanks again!
