### ISSUE TITLE
Issues signing in after manually copying conway folder

### ISSUE THREAD

**Issue by LostInIgnorance** [RobertD502/home-assistant-iocare#53]
When signing in, I am receiving the below error in my logs:

2024-09-10 21:30:21.161 ERROR (MainThread) [custom_components.coway.config_flow] Unable to connect to IoCare: Failed to Log In
2024-09-10 21:34:29.614 ERROR (MainThread) [custom_components.coway.config_flow] Unable to connect to IoCare: Failed to Log In

**Comment by RobertD502** [comment]
Turn off IPv6 on Home Assistant. Some users reported when IPv6 is enabled in Home Assistant, it causes issues with logging in.

**Comment by LostInIgnorance** [comment]
I have that already off as IPV6 seems to cause more issues than it solves on a home network. I am only using IPV4. I am also using Home Assistant's appliance.

**Comment by LostInIgnorance** [comment]
@RobertD502 Thank you for your help. I am finding the manual add to custom components did not yield the same integration as using HACS. I was successfully able to add the integration after installing HACS and then your package/repository.

Thank you for your fast responses. Keep up the great work on this!!!
