### ISSUE TITLE
iocare install incomplete

### ISSUE THREAD

**Issue by jjdonn** [RobertD502/home-assistant-iocare#6]
installed via hacs.  device showing but device page only lists upload entity.  See attached diagnostics.  Question:  How to resolve so other entities can be configured with my coway login?
[config_entry-hacs-62c84b8db1c01c5fb35b6829914f14f6.json.txt](https://github.com/RobertD502/home-assistant-iocare/files/8548611/config_entry-hacs-62c84b8db1c01c5fb35b6829914f14f6.json.txt)

**Comment by RobertD502** [comment]
I'm not entirely sure I understand what you are saying. Would you mind telling me what Coway device you have (model) and provide a screenshot of the devices page.

**Comment by jjdonn** [comment]
See atch device page screenpic.   
![Untitled picture](https://user-images.githubusercontent.com/11546897/165172044-460948ea-9410-4714-9254-081d8a5d8a18.png)
Originally only the Coway IoCare device  showed on this page,  and I filed this ticket to get clarification.   Eventually was able to get (not sure exactly how) the AIRMEGA 400S device from Coway and this resolves the issue.

**Comment by RobertD502** [comment]
Just for future reference, it is a lot easier to see what devices are pulled in by and integration by going to the integrations page, and clicking on the devices link specific to the integration.
