### ISSUE TITLE
Index out of range error

### ISSUE THREAD

**Issue by EverythingSmartHome** [RobertD502/home-assistant-iocare#7]
Hey Robert,

Firstly, great job with this!

Testing this with a 300s and works great, I can control everything and sensor information is all populated as it should be.

When turning the fan on or off or changing anything like speeds or presets,I do get an error "Failed to call service fan.turn_on: list index out of range".

However it does turn on and off as it should. Perhaps you have seen this before?

Lewis

**Comment by RobertD502** [comment]
I can't say I have. When you are turning the purifier on/off or changing speed, are you doing this through the UI or manually calling the fan.turn_on, fan.turn_off, fan.set_precentage_service, fan.set_preset_mode services?

**Comment by EverythingSmartHome** [comment]
Just through the UI with the entities created

**Comment by RobertD502** [comment]
For starters, do you happen to have a 300s that shipped with the newer firmware? You can verify this in the app by selecting the "Device Management" tab, followed by "Product Settings". On this page, is there a MCU version listed anywhere? If so then you have a 300s with the newer firmware. If only the serial number is shown then your purifier has the older firmware. 

If you do in fact have the newer firmware, the key corresponding to the fan speed (within the API response) may be reporting a value that isn't present in the older firmware. If this is the case then it would be the cause of the list index out of range error.

**Comment by EverythingSmartHome** [comment]
I just checked - I seem to have the older firmware, not seeing any mention of MCU on that page.

Here is one of the errors in the HA log:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 137, in _handle_refresh_interval
    await self._async_refresh(log_failures=True, scheduled=True)
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 268, in _async_refresh
    update_callback()
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", line 328, in _handle_coordinator_update
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 410, in state
    value = self.native_value
  File "/config/custom_components/coway/sensor.py", line 71, in native_value
    return self.coordinator.data[self._device].filters[0]["life_level_pct"]
IndexError: list index out of range
```

**Comment by RobertD502** [comment]
Looks like it is all related to the Prefilter sensor. Whenever you control the purifier, all entities get updated which is why the prefilter error is showing up even when doing things such as changing speed, changing the preset, etc.


To narrow it down, can you please go into the coway folder (within your custom_components folder) and open sensor.py.

There add `_LOGGER.error(self.coordinator.data[self._device].filters[0]["life_level_pct"])` under __init__ within the Prefilter class such as this:

![image](https://user-images.githubusercontent.com/52541649/165181012-3e6dab0d-aa4c-4c9c-abc0-a557f6ddd0f6.png)

Save the changes. Then restart Home Assistant and you should see the integration log an error containing the value that is fetched for the prefilter from coway's servers. Whenever you change percentage, power, and preset, this should continue to get logged. Let me know what value is being logged.

**Comment by EverythingSmartHome** [comment]
Thanks, tried that, unfortunately doesn't seem to output the value it supposed to but gives me this in the logs:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/coway/sensor.py", line 29, in async_setup_entry
    sensors.append(PreFilter(coordinator, idx))
  File "/config/custom_components/coway/sensor.py", line 46, in __init__
    _LOGGER.error(self.coordinator.data[self._device].filters[0]["life_level_pct"])
IndexError: list index out of range
```

**Comment by RobertD502** [comment]
Thanks that helps. This is letting me know that the API isn't properly returning the filter. Lets see everything that the API is pulling in for filters:

Take the line that I just had you put into the sensor.py file and replace it with `_LOGGER.error(self.coordinator.data[self._device].filters)`. Save and restart home assistant. Locate the error that is logged and please share it here. The log should contain Korean like this:

![image](https://user-images.githubusercontent.com/52541649/165185089-7a4f1037-fcff-48f6-a489-f3d0b590a1ea.png)

**Comment by EverythingSmartHome** [comment]
So this now gives me the following empty error:

![image](https://user-images.githubusercontent.com/53482654/165392616-860b073e-9c65-41e2-a057-98b4405bdf87.png)

As well as another error logged:
```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 799, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 532, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 570, in _async_write_ha_state
    state = self._stringify_state(available)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 538, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/sensor/__init__.py", line 410, in state
    value = self.native_value
  File "/config/custom_components/coway/sensor.py", line 71, in native_value
    return self.coordinator.data[self._device].filters[0]["life_level_pct"]
IndexError: list index out of range
```

**Comment by RobertD502** [comment]
This further confirms that the backend library isn't returning anything regarding the pre filter and max2 filter. Are you comfortable with python and running a test file with the backend library? If not, the only other way I would be able to investigate what Coway's servers are returning is by using your credentials myself (the password you can change right after/I won't be changing the speed, power, mode, or anything like that).

**Comment by EverythingSmartHome** [comment]
Sure I'm happy to help, let me know what you need me to do!

**Comment by RobertD502** [comment]
What's a good e-mail to reach you at? Don't want your credentials exposed here.

**Comment by EverythingSmartHome** [comment]
I'm happy to run the python if that's good for you, I have a little experience with it

**Comment by RobertD502** [comment]
Hey Lewis,

I apologize for getting back to you so late!

Things to do:

1. Go to the [pyiocare repo](https://github.com/RobertD502/pyiocare/tree/everything_smart_home) and download the repo by pressing on the `code` button and selecting `download as zip` (make sure you are downloading the `everything_smart_home` branch that I created).
2. Unzip the file and you should now see the pyiocare folder.
3. Within that folder, you will see a `test.py` file. Open the file up for editing and replace `email` with your account email and `password` with your account password. Be sure your email and password are both surrounded by single quotation marks like `email` and `password` are in the original file in order to pass those in as strings. Once you have done so save the file.
4. Before doing anything else, you will need to install 3 dependencies using pip3:

- aiohttp
- pycryptodome
- yarl

5. Now that you have the dependencies installed, you will need to `run the test.py` file. I see that you are a windows user based on your youtube videos, so just run the test.py file from a command prompt by either navigating to the folder it is located in via the command prompt and then typing `test.py` or by entering the full file location (I know on mac you can do that by dragging the file to the terminal. I believe you should be able to do the same with the windows command prompt). You should get an output that contains all the data from coway's filter endpoint.
6. Paste that output here.

**Comment by EverythingSmartHome** [comment]
No problem at all. Here is the output:
```
{'body': {'analysisEndDt': '202204282110', 'closeOnSceduleId': -1, 'closeOffSceduleId': -1, 'temperature': 0.0, 'humidity': 0, 'filterList': [], 'schedules': [], 'prodStatus': [{'dustSensitivity': '', 'reservation': '', 'airVolume': '0', 'light': '0', 'vocsGrade': '', 'pollenMode': '0', 'dustPollution': '1', 'lightDetail': '', 'prodMode': '2', 'power': '0', 'AICare': '', 'Humidification': ''}], 'pm10Graph': [{'graphhighvalue': '33', 'place': 'in', 'msrdt': '202204281510', 'graphvalue': '3'}, {'graphhighvalue': '33', 'place': 'in', 'msrdt': '202204281520', 'graphvalue': '4'}, {'graphhighvalue': '28', 'place': 'in', 'msrdt': '202204281530', 'graphvalue': '3'}, {'graphhighvalue': '0', 'place': 'in', 'msrdt': '202204281540', 'graphvalue': '0'}, {'graphhighvalue': '26', 'place': 'in', 'msrdt': '202204281550', 'graphvalue': '3'}, {'graphhighvalue': '33', 'place': 'in', 'msrdt': '202204281600', 'graphvalue': '4'}, {'graphhighvalue': '29', 'place': 'in', 'msrdt': '202204281610', 'graphvalue': '5'}, {'graphhighvalue': '27', 'place': 'in', 'msrdt': '202204281620', 'graphvalue': '3'}, {'graphhighvalue': '25', 'place': 'in', 'msrdt': '202204281630', 'graphvalue': '4'}, {'graphhighvalue': '26', 'place': 'in', 'msrdt': '202204281640', 'graphvalue': '3'}, {'graphhighvalue': '24', 'place': 'in', 'msrdt': '202204281650', 'graphvalue': '4'}, {'graphhighvalue': '26', 'place': 'in', 'msrdt': '202204281700', 'graphvalue': '3'}, {'graphhighvalue': '26', 'place': 'in', 'msrdt': '202204281710', 'graphvalue': '5'}, {'graphhighvalue': '25', 'place': 'in', 'msrdt': '202204281720', 'graphvalue': '3'}, {'graphhighvalue': '27', 'place': 'in', 'msrdt': '202204281730', 'graphvalue': '3'}, {'graphhighvalue': '27', 'place': 'in', 'msrdt': '202204281740', 'graphvalue': '5'}, {'graphhighvalue': '27', 'place': 'in', 'msrdt': '202204281750', 'graphvalue': '5'}, {'graphhighvalue': '2', 'place': 'in', 'msrdt': '202204281800', 'graphvalue': '0'}, {'graphhighvalue': '26', 'place': 'in', 'msrdt': '202204281810', 'graphvalue': '3'}, {'graphhighvalue': '26', 'place': 'in', 'msrdt': '202204281820', 'graphvalue': '3'}, {'graphhighvalue': '27', 'place': 'in', 'msrdt': '202204281830', 'graphvalue': '3'}, {'graphhighvalue': '27', 'place': 'in', 'msrdt': '202204281840', 'graphvalue': '3'}, {'graphhighvalue': '27', 'place': 'in', 'msrdt': '202204281850', 'graphvalue': '3'}, {'graphhighvalue': '27', 'place': 'in', 'msrdt': '202204281900', 'graphvalue': '3'}, {'graphhighvalue': '27', 'place': 'in', 'msrdt': '202204281910', 'graphvalue': '3'}, {'graphhighvalue': '26', 'place': 'in', 'msrdt': '202204281920', 'graphvalue': '3'}, {'graphhighvalue': '26', 'place': 'in', 'msrdt': '202204281930', 'graphvalue': '3'}, {'graphhighvalue': '29', 'place': 'in', 'msrdt': '202204281940', 'graphvalue': '4'}, {'graphhighvalue': '45', 'place': 'in', 'msrdt': '202204281950', 'graphvalue': '5'}, {'graphhighvalue': '28', 'place': 'in', 'msrdt': '202204282000', 'graphvalue': '3'}, {'graphhighvalue': '42', 'place': 'in', 'msrdt': '202204282010', 'graphvalue': '4'}, {'graphhighvalue': '26', 'place': 'in', 'msrdt': '202204282020', 'graphvalue': '4'}, {'graphhighvalue': '0', 'place': 'in', 'msrdt': '202204282030', 'graphvalue': '0'}, {'graphhighvalue': '27', 'place': 'in', 'msrdt': '202204282040', 'graphvalue': '3'}, {'graphhighvalue': '0', 'place': 'in', 'msrdt': '202204282050', 'graphvalue': '0'}, {'graphhighvalue': '26', 'place': 'in', 'msrdt': '202204282100', 'graphvalue': '3'}, {'graphhighvalue': '28', 'place': 'in', 'msrdt': '202204282110', 'graphvalue': '3'}], 'analysisStartDt': '202204281510', 'elapsedHeartServiceDate': None, 'nextHeartService': None, 'IAQ': [{'co2': '0', 'inairquality': '20', 'humidity': '', 'dustpm25': '0', 'temperature': '', 'dustpm10': '0', 'dustpm1': '', 'vocs': '0'}], 'OAQ': []}, 'header': {'accessToken': '', 'result': True, 'trcode': 'CWIA0120'}}
Traceback (most recent call last):
  File "c:\Users\Lewis\Downloads\pyiocare-everything_smart_home\pyiocare-everything_smart_home\test.py", line 15, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Users\Lewis\AppData\Local\Programs\Python\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "c:\Users\Lewis\Downloads\pyiocare-everything_smart_home\pyiocare-everything_smart_home\test.py", line 12, in main
    data = await client.async_get_purifiers_data()
  File "c:\Users\Lewis\Downloads\pyiocare-everything_smart_home\pyiocare-everything_smart_home\pyiocare\coway_client.py", line 161, in async_get_purifiers_data
    pre_filter_name = state[2][0][0].get('filterName')
IndexError: list index out of range
```

Looks like the index out of range error is back here too!

P.s - I use Windows mostly for videos as its what most of my audience uses - I actually use Fedora mostly where possible...having said that I did just run it on Windows!!

**Comment by RobertD502** [comment]
Within the IoCare app, on the `Home` tab to be specific....when you scroll to the bottom, does it show the pre filter and max2 filter percentages such as this:



![image](https://user-images.githubusercontent.com/52541649/165842566-7540a4d2-a3ec-474d-a145-df9e7d15bd7c.png)

**Comment by EverythingSmartHome** [comment]
Huh, no it doesn't! The box is there for it but it says "Failed to update the filter information" - I'll see if I can force that somehow

**Comment by RobertD502** [comment]
You may be able to by going to the `device management` tab, then `Product Settings`, then `pre filter wash frequency`, setting it to one of the options and saving.

**Comment by EverythingSmartHome** [comment]
Apologies for the delay, I opened a support ticket to see why those values weren't available in the app. They fixed this for me with a firmware update and now the errors seems to be resolved - so looks like no bug was there. Thanks again for the help with that!

**Comment by RobertD502** [comment]
Hmmmm since they updated your firmware...I'm curious to know, are you still seeing an AQI sensor that is reporting values in Home Assistant? Asking because some models that users recently received with newer firmware were not reporting AQI on the quality server endpoint at all!

**Comment by EverythingSmartHome** [comment]
Yes I can see AQI OK - no VOC level (or it's just indicated at 0) though:

![Screenshot_20220501-115231](https://user-images.githubusercontent.com/53482654/166142796-f0eebfdc-cb4e-4fb9-8c04-5447de88a536.png)

**Comment by RobertD502** [comment]
That's just always listed at 0 among other things. They report it, but it is always 0. Left it there in case they do start actually reporting values at some point. There are other things such as humidity which I don't pull in since that doesn't have a value, but also the purifier doesn't have a sensor capable of reporting that.
