### ISSUE TITLE
Can't control AP-1512HHS anymore

### ISSUE THREAD

**Issue by smmalis37** [RobertD502/home-assistant-iocare#8]
This started a few days ago, and it's also important to note that the official IOCare app has the same issue for me, but I don't know what to do to debug it. Both Home Assistant and the app are able to see the status of the filter, live updates and all, however they're both unable to change anything. When I try, nothing happens. If I change something manually on the filter it is reflected immediately in the UI. It's as if the device has flipped into a read-only mode or something. The weirdest thing is that nothing shows any error messages, the home assistant logs are empty, and as a result I don't know what to try. I know this isn't an issue with this integration per-se, but I was hoping someone might have some debugging suggestions.

**Comment by RobertD502** [comment]
Given that it isn't working on the IOCare app, it would be hard to debug without sniffing the communication between the app and coway servers. I don't have this model, so, I can't do this without access to an account that has the model. Perhaps there are other users out there that also have this model, are experiencing the same problem, and can MITM the communication.

**Comment by RobertD502** [comment]
Not a problem at all. I wasn't aware that model even worked with this integration.
