### ISSUE TITLE
Compatibility for Python 3.10

### ISSUE THREAD

**Issue by npawelek** [RobertD502/home-assistant-iocare#9]
Are there any plans to update compatibility for Python 3.10? This looks to break when loading the latest version of Home Assistant (2022.7.x).

```
2022-07-15 12:56:37 ERROR (MainThread) [homeassistant.setup] Setup failed for custom integration coway: Unable to import component: No module named 'iocare'
```

**Comment by RobertD502** [comment]
![image](https://user-images.githubusercontent.com/52541649/179285140-b3c2d7cb-330a-4b29-b7a2-c40cdb14781e.png)

Working fine in 2022.7.5

**Comment by npawelek** [comment]
Interesting. I'll try deleting the integration and reinstalling.

**Comment by npawelek** [comment]
Seems to have fixed. Appreciate the quick reply!
